version: '3.1'

services:
  db:
    image: mariadb
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
  adminer:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5555:80
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: "db"
    depends_on:
      - db